baseURL = "https://corona-stat.lt"
title = "Corona-Stat.lt"
#copyright = "Copyright © rancia and the Hugo Authors; all rights reserved."
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-162832540-1"
DisqusShortname = "corona-stat-lt"
theme = "hugo-theme-chunky-poster"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"  
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "ltstat"
    name = "Lietuvos statistika"
    url = "/ltstat/"
    weight = 2
  [[menu.main]]
    identifier = "eustat"
    name = "Europos statistika"
    url = "/eustat/"
    weight = 3
  [[menu.main]]
    identifier = "wstat"
    name = "Pasaulio statistika"
    url = "/wstat/"
    weight = 4

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[params]
#author = "Corona-Stat.lt"
description = "COVID-19 statistika, ekonomiminės, socialinės bei politinės įžvalgos"
#homepageImage = "/images/corona-stat-logo_16_9.png"
share = true
showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = true
    email = "corona-stat@protonmail.com"
    facebook = "https://www.facebook.com/coronastat/"
    #instagram = "https://stackoverflow.com"
    #github = "https://github.com"


  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = false
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true