---
title: "Lietuvos statistika"
author: "Justas Mundeikis"
date: 2015-07-23T21:13:14-05:00
categories: ["Lietuva"]
tags: ["Lietuva", "statisika"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, collapse = TRUE, error = TRUE, warning = FALSE, message = FALSE)
```

```{r, include=FALSE}
source("./scripts/loading_R_packets.R")
source("./scripts/data_import_GS.R")
source("./scripts/data_import_LT.R")
```

```{r, include=FALSE}
data_world <- read.csv("./data/data_world.csv",header = TRUE,stringsAsFactors = FALSE)%>%
  mutate(date=as.Date(date),
         var=factor(var, levels=c("confirmed", "recovered","deaths")))

data_lt <- read.csv("./data/data_lt.csv",header = TRUE,stringsAsFactors = FALSE)%>%
  mutate(date_confirmation=as.Date(date_confirmation),
         date_infection=as.Date(date_infection))
```

## Bendras atvejų skaičius
```{r, echo=FALSE}
df <- data_world %>%
  filter(CNTR_CODE == "LT")

max.date <- max(df$date)


ggplot(df, aes(x=date, y=value, fill=var))+
  geom_area(alpha=0.5)+
  scale_fill_manual(values=c("red", "green","black"),
                    labels=c("Aktyvūs", "Pasveikę", "Mirę"))+
  scale_x_date(breaks="1 month")+
  scale_y_continuous()+
  labs(title="Atvejų skaičius ir pasiskirstymas",
       subtitle = "Šaltinis: JHCSSE, skaičiavimai: Corona-Stat.lt",
       x="Data",
       y="Skaičius")+
  theme(legend.title=element_blank(),
        legend.position='bottom',
        axis.text.x = element_text(angle = 45, hjust = 1))
```

# Užsikrėtimai

```{r}

max.date <- max(data_lt$date_confirmation)
two_weeks <- max.date-30

df <- data_lt%>%
        filter(date_confirmation>=two_weeks)%>%
        group_by(date_confirmation)%>%
        count(date_confirmation)%>%
        rename(value=n)

ggplot(df,aes(x=date_confirmation, y=value)) +
  geom_bar(stat='identity',
           fill="steelblue")+
  geom_text(aes(label=value, y=value), size=3, vjust=-0.75)+
        scale_x_date(breaks = "2 days")+
  labs(title="Naujų užsikrėtimų skaičius per paskutines 30 dienų",
       subtitle="Šaltinis: NVSC, skaičiavimai: Corona-Stat.lt",
       x="Data", 
       y="Užsikrėtimų skaičius")+
  theme(legend.title=element_blank(),
        legend.position='none',
        axis.text.x=element_text(angle=45, hjust=1))


```


```{r}

df <- data_lt%>%
        group_by(age_group, sex)%>%
        summarise(value=n())%>%
        na.omit()%>%
        mutate(age_group=factor(age_group,
                levels=c("0-9","10-19","20-29","30-39","40-49",
                         "50-59","60-69","70-79","80-89","90-99","100-109")))

ggplot(df, aes(age_group,value, fill=sex))+
        geom_bar(stat="identity",
                 position="dodge")+
              scale_fill_brewer(palette="Set1")+
        labs(title="Atvejai pagal amžiaus kategorijas",
       subtitle="Šaltinis: NVSC, skaičiavimai: Corona-Stat.lt",
                        x="Amžiaus grupė", 
       y="Užsikrėtimų skaičius")+
  theme(legend.title=element_blank(),
        legend.position='bottom',
        axis.text.x=element_text(angle=45, hjust=1))
```


# Mirtys
```{r}

max.date <- max(data_lt$date_confirmation)
two_weeks <- max.date-14

df <- data_lt%>%
        filter(date_confirmation>=two_weeks)%>%
        group_by(age_group, sex)%>%
        summarise(value=n())%>%
        na.omit()%>%
        mutate(age_group=factor(age_group,
                levels=c("0-9","10-19","20-29","30-39","40-49",
                         "50-59","60-69","70-79","80-89","90-99","100-109")))

ggplot(df, aes(age_group,value, fill=sex))+
        geom_bar(stat="identity",
                 position="dodge")+
            scale_fill_brewer(palette="Set1")+
        labs(title="Atvejai pagal amžiaus kategorijas, paskutinės 14 dienų",
       subtitle="Šaltinis: NVSC, skaičiavimai: Corona-Stat.lt",
                        x="Amžiaus grupė", 
       y="Užsikrėtimų skaičius")+
  theme(legend.title=element_blank(),
        legend.position='bottom',
        axis.text.x=element_text(angle=45, hjust=1))
```


```{r}
df <- data_lt%>%
        filter(result=="Mirė")%>%
        group_by(age_group, sex)%>%
        summarise(value=n())%>%
        na.omit()%>%
        mutate(age_group=factor(age_group,
                levels=c("0-9","10-19","20-29","30-39","40-49",
                         "50-59","60-69","70-79","80-89","90-99","100-109")))

ggplot(df, aes(age_group,value, fill=sex))+
        geom_bar(stat="identity",
                 position="dodge")+
            scale_fill_brewer(palette="Set1")+
        labs(title="Mirusieji pagal amžiaus kategorijas, paskutinės 14 dienų",
       subtitle="Šaltinis: NVSC, skaičiavimai: Corona-Stat.lt",
                        x="Amžiaus grupė", 
       y="Užsikrėtimų skaičius")+
  theme(legend.title=element_blank(),
        legend.position='bottom',
        axis.text.x=element_text(angle=45, hjust=1))
```

